build:
  tasks:
    - name: setup
      command: $WORKING_DIR/setup.sh
      only_if: test "$WERCKER" = "true"
    - name: Make $HOME/.ssh directory
      command: mkdir -p $HOME/.ssh
      only_if: test "$WERCKER" = "true"
    - name: Put SSH publick key
      command: echo "$DIGITALOCEAN_SSH_KEY_PUBLIC" > $HOME/.ssh/id_rsa.pub
      only_if: test "$WERCKER" = "true"
    - name: Put SSH private key
      command: echo $DIGITALOCEAN_SSH_KEY_PRIVATE > $HOME/.ssh/id_rsa
      only_if: test "$WERCKER" = "true"
    - name: chmod 600 $HOME/.ssh/id_rsa
      command: chmod 600 $HOME/.ssh/id_rsa
      only_if: test "$WERCKER" = "true"
    - name: Parallel builds each OSes
      parallel:
      - include: coreos.yml
      - include: centos65.yml
      - include: centos72.yml
      - include: ubuntu1404.yml
      - include: freebsd101.yml
  cleanup:
    - name: vagrant destroy
      command: vagrant destroy --force
      directory: $WORKING_DIR

notify:
  - type: slack
    channel: serverspec
    url: $SLACK_WEBHOOK_URL
    icon_url: https://raw.githubusercontent.com/serverspec/serverspec-integration-test/master/walter.png
    username: Walter
